### ISSUE TITLE
Error when calling ionic platform add on Cordova 6.x

### ISSUE THREAD

**Issue by SebastianSchirmer** [mhartington/cordova-config-utils#15]
When running on Cordova 6, ionic platform add triggers after_prepare hooks to run. When newly adding a platform, the cordova-config-utils hooks is triggered but throws an error as there is not config.xml yet available in the platforms folder. Only after ionic build the platform-specific config.xml is available and no error is thrown.

This issue does not occur when running ionic state reset, only when running ionic platform add.

See this issue for reference: https://issues.apache.org/jira/browse/CB-10641

**Comment by ivangrestorres** [comment]
The same problem @leschirmeur @mhartington

**Comment by mhartington** [comment]
Hmm, this looks like it should be fixed cordova6.1.1?

**Comment by SebastianSchirmer** [comment]
@mhartington I am not sure I understood your comment, do you know that this will be fixed with Cordova 6.1.1 or are you suggesting to raise an issue with the Cordova project?

**Comment by mhartington** [comment]
The issue you've linked to, looks like it has been resolved in cordova 6.1.1. Are you using cordova-cli 6.1.1?

**Comment by SebastianSchirmer** [comment]
I am using cordova 6.1.0 which is, as far as I know, the latest published release version.

**Comment by SebastianSchirmer** [comment]
This is not so much an issue for me right now as we are using ionic state reset but wanted to make you aware of it.

**Comment by SebastianSchirmer** [comment]
Just noticed that Cordova 6.1.1 is out, will try with this version
