### ISSUE TITLE
CordovaApp -> MainActivity with cordova-android v6

### ISSUE THREAD

**Issue by alexpatow** [mhartington/cordova-config-utils#19]
Hi,

I ran into a similar issue to this one earlier: https://github.com/dpa99c/cordova-custom-config/issues/1

It appears that with the latest version of cordova-android (I'm using 6.1.2) the name has changed from "CordovaApp" to "MainActivity" in the android preferences.

I was able to resolve by changing the parent name from:
application/activity[@android:name=\'CordovaApp\']

to:
application/activity[@android:name=\'MainActivity\']

But this would cause breaking changes for anyone not on version 6.

I'd be happy to write the code to make these changes non-breaking if you provide me some guidance on the best way of doing that.

Thanks,

Alex

**Comment by mhartington** [comment]
https://github.com/mhartington/cordova-config-utils/commit/1aacd59e2473c3d98ec27206cd5527d1fd13c868

I'm no longer maintaining this.
