### ISSUE TITLE
trouble updateing to npm 3+

### ISSUE THREAD

**Issue by note89** [mhartington/cordova-config-utils#8]
I updated to npm3 an then you have to keep track of all dependencies yourself if i understand correctly. 
But i get this error 

docker@hal9001:/AheadIonic$ npm install -g plist
npm WARN engine xmlbuilder@2.2.1: wanted: {"node":"0.8.x || 0.10.x"} (current: {"node":"4.2.2","npm":"3.3.12"})
/usr/local/lib
└── plist@1.1.0 

docker@hal9001:/AheadIonic$ ionic run android  
Running command: /AheadIonic/hooks/after_prepare/011_update_config.js /AheadIonic
module.js:339
    throw err;
    ^

Error: Cannot find module 'plist'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/AheadIonic/hooks/after_prepare/011_update_config.js:8:13)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
ERROR running one or more of the platforms: Error: Hook failed with error code 1: /AheadIonic/hooks/after_prepare/011_update_config.js
You may not have the required environment or OS to run this project

when i try to install cordova-config-utils. But i have them in /usr/local/lib/node_modules$
npm WARN EPEERINVALID cordova-config-utils@2.1.0 requires a peer of elementtree@^0.1.6 but none was installed.
npm WARN EPEERINVALID cordova-config-utils@2.1.0 requires a peer of lodash@^3.10.1 but none was installed.
npm WARN EPEERINVALID cordova-config-utils@2.1.0 requires a peer of plist@^1.1.0 but none was installed.
npm WARN EPEERINVALID cordova-config-utils@2.1.0 requires a peer of xcode@^0.8.2 but none was installed.

**Comment by mhartington** [comment]
Hmm, possibly a bad install? I have npm3 and it's been working fine for me.

**Comment by mhartington** [comment]
Closing since lack of activity.
